version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf  # Add custom Nginx config

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads  # Share uploads directory with host
    environment:
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=usam.sersultanov@gmail.com
      - MAIL_PASSWORD=zkkb dbpd hnqg ckxv
      - MAIL_DEFAULT_SENDER=usam.sersultanov@gmail.com

  updater:
    image: python:3.9-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: python update_css_colors.py
